### ISSUE TITLE
demand-express builds not working

### ISSUE THREAD

**Issue by xtazy** [rangle/angular-ssr#51]
Hello,

When I run 'npm run build:client', I get the following errors:
`$ npm run build:client

> angular-ssr-demand-express-example@1.0.0 build:client C:\cygwin\tmp\ssr\examples\demand-express
> webpack

ts-loader: Using typescript@2.4.1 and C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
Hash: b482a775fce5eccbb399
Version: webpack 2.6.1
Time: 62498ms
     Asset       Size  Chunks                    Chunk Names
    app.js    4.67 MB       0  [emitted]  [big]  client
app.js.map    5.56 MB       0  [emitted]         client
index.html  272 bytes          [emitted]
  [16] ./~/@angular/platform-browser/@angular/platform-browser.es5.js 141 kB {0} [built]
  [19] ./~/@angular/common/@angular/common.es5.js 130 kB {0} [built]
  [29] ./~/@angular/material/@angular/material.es5.js 759 kB {0} [built]
  [40] ./~/@angular/forms/@angular/forms.es5.js 204 kB {0} [built]
  [42] ./~/@angular/router/@angular/router.es5.js 214 kB {0} [built]
  [58] ./~/process/browser.js 5.42 kB {0} [built]
 [113] ./app/blog/module.ts 1.55 kB {0} [built]
 [119] ./app/main.ts 360 bytes {0} [built]
 [122] ./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 5.88 kB {0} [built]
 [129] ./~/hammerjs/hammer.js 73.8 kB {0} [built]
 [143] ./~/reflect-metadata/Reflect.js 48 kB {0} [built]
 [398] ./app/blog/index.ts 301 bytes {0} [built]
 [404] ./app/root.module.ts 3.33 kB {0} [built] [1 error]
 [407] ./~/zone.js/dist/zone.js 96 kB {0} [built]
 [408] multi ./app/main.ts 28 bytes {0} [built]
    + 394 hidden modules

WARNING in ./~/@angular/core/@angular/core.es5.js
5704:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
5720:15-102 Critical dependency: the request of a dependency is an expression

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\@angular\tsc-wrapped\src\vinyl_file.d.ts
(11,15): error TS2304: Cannot find name 'Buffer'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\@angular\tsc-wrapped\src\vinyl_file.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\angular-ssr\build\transformation\promise.d.ts
(2,68): error TS2503: Cannot find namespace 'NodeJS'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\angular-ssr\build\transformation\promise.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\@types\express-serve-static-core\index.d.ts
(19,23): error TS2307: Cannot find module 'http'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\@types\express-serve-static-core\index.d.ts
(6,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\rxjs\observable\dom\WebSocketSubject.d.ts
(24,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\node_modules\rxjs\Subject.d.ts
(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\server\paths.ts
(3,34): error TS2304: Cannot find name '__dirname'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\server\http.ts
(12,12): error TS2304: Cannot find name 'require'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\server\http.ts
(18,16): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\test-runner.ts
(22,28): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\test-runner.ts
(26,11): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\test-runner.ts
(47,5): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\test-runner.ts
(52,5): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\server.ts
(1,21): error TS2307: Cannot find module 'child_process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\environment.ts
(1,21): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\environment.ts
(5,24): error TS2304: Cannot find name 'process'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\client.ts
(1,15): error TS2304: Cannot find name 'require'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\ci\client.ts
(3,16): error TS2304: Cannot find name 'require'.

ERROR in ./app/locale/service.ts
(19,5): error TS2322: Type 'ReplaySubject<string>' is not assignable to type 'Observable<string>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<string, R>) => Observable<string>' is not assignable to type '<R>(operator: Operator<string, R>) => Observable<R>'.
      Type 'Observable<string>' is not assignable to type 'Observable<R>'.
        Type 'string' is not assignable to type 'R'.

ERROR in ./app/locale/selector.component.ts
(9,13): error TS2304: Cannot find name 'require'.

ERROR in ./app/blog/blog.component.ts
(15,13): error TS2304: Cannot find name 'require'.

ERROR in ./app/blog/blog.component.ts
(16,12): error TS2304: Cannot find name 'require'.

ERROR in ./app/blog/blog.component.ts
(28,5): error TS2322: Type 'Observable<ArrayLike<Blog>>' is not assignable to type 'Observable<Blog[]>'.
  Type 'ArrayLike<Blog>' is not assignable to type 'Blog[]'.
    Property 'find' is missing in type 'ArrayLike<Blog>'.

ERROR in ./app/blog/blog.component.ts
(36,5): error TS2322: Type 'Observable<ArrayLike<Blog>>' is not assignable to type 'Observable<Blog[]>'.

ERROR in ./app/root.module.ts
(28,77): error TS2304: Cannot find name 'require'.

ERROR in ./app/root.component.ts
(9,13): error TS2304: Cannot find name 'require'.

ERROR in ./app/root.component.ts
(11,5): error TS2304: Cannot find name 'require'.

ERROR in ./app/root.component.ts
(12,5): error TS2304: Cannot find name 'require'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'chalk'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'node'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'node-fetch'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'source-map'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'tapable'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'uglify-js'.

ERROR in C:\cygwin\tmp\ssr\examples\demand-express\tsconfig.json
error TS2688: Cannot find type definition file for 'webpack'.
Child html-webpack-plugin for "index.html":
       [0] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 269 bytes {0} [built]

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:client"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-ssr-demand-express-example@1.0.0 build:client: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-ssr-demand-express-example@1.0.0 build:client script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-ssr-demand-express-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-ssr-demand-express-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-ssr-demand-express-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin\tmp\ssr\examples\demand-express\npm-debug.log`

**Comment by buu700** [comment]
You may just need to [upgrade rxjs to 6.0.0-alpha (or downgrade typescript to 2.3.4)](https://github.com/ReactiveX/rxjs/issues/2539) and install @types packages for all the mentioned missing type definitions (@types/node, @types/uglify-js, etc.).
