### ISSUE TITLE
dynamic data rendiring

### ISSUE THREAD

**Issue by adwaer** [rangle/angular-ssr#58]
Hello!
Ur package good working!
But.. :)
How to make my dynamic data render? I have read about preboot, and prerendering (where to pass this code?..)

I have custom dynamic text directive and i want ssr to render it. There my directive module:
[localization.zip](https://github.com/rangle/angular-ssr/files/1151366/localization.zip)

App.module looks like root.module.ts in the demand-express

**Comment by clbond** [comment]
The issue is with assignment of `innerText`. I don't think that works with domino. Try using a regular Angular way of rendering the text eg `{{localizedText | async}}` in your template.
