### ISSUE TITLE
ng-render holds on first info log

### ISSUE THREAD

**Issue by Simon-Bru** [rangle/angular-ssr#59]
Hello, 
I have an issue when  I run 
`ng-render -p src/tsconfig.json`
The console holds on the first log: 

`[info] Rendering application from source (working path: /tmp/f972bac77967d) [=0l`

I see the working directory is wrong as it should be "/user/me/myapp" or something but I didn't figure out how to fix it.
My application has been created with angular-cli, and uses embedded webpack config (it's not ejected). 
Thanks in advance for any help

Simon

**Comment by clbond** [comment]
The directory is right - it builds to a temporary directory. If it never succeeds and just hangs, that's very unusual. What is your app doing on startup? Can i see the code?
