### ISSUE TITLE
No ssr on certain routes.

### ISSUE THREAD

**Issue by ffluffyhedgehog** [rangle/angular-ssr#69]
Hi!

Some of routes in my application are dynamic and different for each user. How do I protect these routes from being server-side rendered?

**Comment by clbond** [comment]
@ffluffyhedgehog Just specify *`server: false`* in the route configuration itself. Any route subtree which you do not want to be server-side rendered. Alternatively, you can use `--blacklist=true` to _exclude all routes from ssr by default_, and then *`server: true`* in the route configuration to note that you *do* wish to render that route. Only route trees with `server: true` will be rendered if you use `--blacklist`.
