### ISSUE TITLE
Shows content but clears afterwards

### ISSUE THREAD

**Issue by mariohmol** [rangle/angular-ssr#71]
Hi there!

I've been using this module for a while and since i upgraded to the latest version i'm having a weird cenario.

When the page first loads (in a incognito window) it shows me the home content but just after it clears all the content under `<application>` and shows a blank page.

If i refresh everything appears.. i tryied to debug and seems to be executing the onInit on the  `app.component` and there is no errors in console.

The HTML received by the request is with all the elements.. but for some reason when execute the JS it removes.

Really lost here, any ideas ?

**Comment by mariohmol** [comment]
Totally intermitent , trying to remove some html and run again.. sometime loads at first time. some time not.. some times have to open incognito like 5 times to make the error appear.. =(

**Comment by mariohmol** [comment]
I figure it out... basicly i changed my app to be feature style, so i have a bunch of angular modules.. and i had a cycle reference... ( a module calling a service for other modules that was not included as a shared)

using `ng serve` it was working always.. and in ssr was intermitent.. 

anyways.. so far so good!! thanks

**Comment by mariohmol** [comment]
I continue with this issue.. dont know what to do.. 3 days in a row ... testing all day long.. could not make progress.. will drop ssr for now =(

**Comment by mariohmol** [comment]
Hi.. OMG.. i tested so many things.. i think that the last thing that i changes.. was something related to cache and providing app.js ... for some reason the app.js was returning a HTML and not a JS.. 

and now everything makes sense.. why this was intermitent... as some times app.js was not coming.. this was taking the HTML coming from the server and removing it... because was missing the app.js

so.. in the future.. if you have an issue where the page loads and disappear.. now that it might be app.js that was missing

hope not having to reopen this akakakak

**Comment by mariohmol** [comment]
Sorry... but still having this issue... had to disable ssr to make it work =(  .. it works perfect without the ssr

as I said is intermitent..  at least on chrome.. i just saw the in firefox always gives this error... load the html from the `/` request and after loads the `app.js` it removes everything from `<aplication` 

if you would like to have access to a live version with the error.. please send me a email

**Comment by mariohmol** [comment]
When i remove `builder.preboot(true)` it seems to be working again..

**Comment by misticwonder** [comment]
I have the same error. How to fix preboot? What version of preboot can we use with ssr?

**Comment by ktersius** [comment]
I experienced something similar, it goes away if you do a hard refresh or disable caching in chrome devtools. I think it is some sort of timing issue because if you throttle the chrome speed in dev-tools all seems to work again.

**Comment by mariohmol** [comment]
@ktersius indeed.. i experienced the same.. but even ith hard refresh.. some times it gave me the same error.. did u try to remove the preboot to see if that goes away?

**Comment by clbond** [comment]
This may mean your application is failing to boot properly. At startup, we create a second root `<application>` (eg) element and once it is populated with rendered content, preboot hides the server-provided root tag and makes visible the client-built one. If it is disappearing, I would try debugging your application bootstrap process. And where are you calling `preboot.complete()` from?

**Comment by mariohmol** [comment]
Thanks for answering! Is this correct?

```
const { prebootClient } = require('preboot/__build/src/browser/preboot_browser');
export class AppModule {
  constructor(router: Router, zone: NgZone) {
    if (typeof prebootstrap === 'undefined') {
      return;
    }

    const finished = Observable.combineLatest(router.events, zone.onMicrotaskEmpty);

    const subscription = finished.subscribe(([event, stable]) => {
      if (stable === false) {
        return;
      }

      switch (true) {
        case event instanceof NavigationError:
        case event instanceof NavigationEnd:
          setImmediate(() => prebootClient().complete());

          subscription.unsubscribe();
          break;
        default:
          break;
      }
    });
  }
}
```

**Comment by misticwonder** [comment]
This problem only in chrome browser with browser cache enabled.

**Comment by clbond** [comment]
Can I have access to your code? Are there uncaught exceptions being thrown (either on the server or the client)? It's impossible for me to debug without the code.

**Comment by mariohmol** [comment]
Hi.. yes i know.. its hard.. but is no errors at all.. if you would like to.. we can do a call and i show you what is happening.. there is my email in my profile.. just let me know

**Comment by clbond** [comment]
I have removed `setImmediate` from the example. Can you tell me if this fixes your issue? Perhaps you are using a browser that doesn't support `setImmediate`

**Comment by mariohmol** [comment]
Guys, i'm not experiencing this anymore.. even putting preboot back... thanks anyway =)
