### ISSUE TITLE
SSR Performance App Startup and Rendering Times

### ISSUE THREAD

**Issue by ktersius** [rangle/angular-ssr#74]
We are using the angular-ssr project to implement our SSR solution. In doing some tests we felt that we should look into getting the most performance out of the SSR solution.

I noticed that all samples are using JIT compilation. Is AOT for the server side rendered application possible? I tried looking around but did not see any sample webpack configurations on how one would accomplish this. 

I noticed that there is an applicationBuilderFromModuleFactory that can be used to speed up app start up performance but I'm also not sure how to make use of it. In experimentation I noticed that the app is started on each request and we would like to reduce this startup time as much as possible.

Can you please provide some guidance or pointers on this?

**Comment by clbond** [comment]
JiT compilation is only done on server startup. From then on, the compiled application is kept in memory and it is always bootstrapped from the precompiled in-memory ('AoT') version.
