### ISSUE TITLE
Error on postbuild:ng-render

### ISSUE THREAD

**Issue by SwamyKottur** [rangle/angular-ssr#75]
@clbond  

{ Error: Hash: f035cd159f5aa4b9d6aa
   Version: webpack 3.5.6
   Time: 3203ms
      Asset     Size  Chunks  Chunk Names
       0.js  1.08 kB       0  app/app.module
   0.js.map  6.51 kB       0  app/app.module
   [Cos1] ./src/app/app.module.ts 509 bytes {0} [built] [failed] [1 error]
      [0] multi ./app/app.module.ts 28 bytes {0} [built]

   ERROR in ./src/app/app.module.ts
   Module build failed: TypeError: Cannot read property 'newLine' of undefined

No where in the code we have newLine, except in dist/vendor.js that too in the comments section of a function

FYI: This project is based out of Angular-Cli project
Any help on this appreciated

**Comment by clbond** [comment]
Your TypeScript version is out of date. Bring it up to date (2.3 i think)
